apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: traefik
spec:
  compress: {}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: elife-oauth-auth
  namespace: traefik
spec:
  forwardAuth:
    address: "${oauth2_proxy_auth_url}"
    trustForwardHeader: true
    authResponseHeaders:
      - "X-Auth-Request-User"
      - "X-Auth-Request-Email"
      - "Set-Cookie"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: elife-oauth-signin
  namespace: traefik
spec:
  errors:
    status:
      - "401"
    service:
      name: oauth2-proxy
      namespace: infra
      port: 80
    query: "/oauth2/start"
