apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
- namespace.yaml
- source.yaml
- release.yaml
- global-middlewares/compress.yaml
- global-middlewares/elife-oauth.yaml
