apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 38.0.2
  interval: 1h0m0s
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  values:
    logs:
      general:
        format: json
      access:
        enabled: true
        format: json
    deployment:
      replicas: 5
      additionalContainers:
      - name: nginx-utils
        image: nginx:1.29.4
        volumeMounts:
        - name: nginx-utils-config
          mountPath: /etc/nginx/conf.d
      additionalVolumes:
      - name: nginx-utils-config
        configMap:
          name: nginx-utils-config
    ingressClass:
      name: traefik
      enabled: true
      isDefaultClass: false
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        ingressClass: traefik
        enabled: true
        allowEmptyServices: true
        allowExternalNameServices: true
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "false"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    ports:
      web:
        middlewares:
          - traefik-compress@kubernetescrd
        proxyProtocol:
          trustedIPs:
            - "10.0.0.0/16"
        forwardedHeaders:
          trustedIPs:
            - "10.0.0.0/16"
      websecure:
        middlewares:
          - traefik-compress@kubernetescrd
        proxyProtocol:
          trustedIPs:
            - "10.0.0.0/16"
        forwardedHeaders:
          trustedIPs:
            - "10.0.0.0/16"
