# Mitigation for CVE-2025-64459 https://github.com/elifesciences/issues/issues/9443
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mitigate-cve-2025-64459
  namespace: traefik
spec:
  ipWhiteList:
    sourceRange:
      - "127.0.0.1/32"
# To apply as mitigation for an ingress, apply to a sidecar ingress:
#
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: api-gateway-mitigate-cve-2025-64459
#   namespace: journal--test
#   annotations:
#    traefik.ingress.kubernetes.io/router.priority: "100"
#    traefik.ingress.kubernetes.io/router.rule: >-
#      Host(`api.test.elifesciences.org`) &&
#      (QueryRegexp(`_connector`, `.*`) || QueryRegexp(`_negated`, `.*`))
#    traefik.ingress.kubernetes.io/router.middlewares: traefik-mitigate-cve-2025-64459@kubernetescrd
# spec:
#   rules:
#   - host: "api.test.elifesciences.org"
#     http:
#       paths:
#       - path: /
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: api-gateway-web
#             port:
#               number: 80
#   tls:
#   - secretName: api-gateway-tls
#     hosts:
#     - "api.test.elifesciences.org"
