apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-redirect
  namespace: test-redirect
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: 'return 302 https://bbc.co.uk/;'
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-www-to-non-www@kubernetescrd,traefik-elife-oauth@kubernetescrd,test-redirect-test-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: test-redirect.${cluster_domain}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: http-svc
            port:
              number: 80
  - host: www.test-redirect.${cluster_domain}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: http-svc
            port:
              number: 80
  tls:
  - hosts:
    - test-redirect.${cluster_domain}
    - www.test-redirect.${cluster_domain}
    secretName: test-redirect.${cluster_domain}-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-redirect
  namespace: test-redirect
spec:
  redirectRegex:
    regex: ^https?://[^/]+(.*)
    replacement: https://bbc.co.uk$${1}
    permanent: true
