apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-redirect
resources:
- namespace.yaml
- deploy.yaml
- service.yaml
- ingress-redirect.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: test-redirect
    app.kubernetes.io/instance: test-redirect
