apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-test
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-elife-oauth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: "traefik-test.flux-test.elifesciences.org"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: traefik-test
                port:
                  number: 5678
  tls:
  - hosts:
    - "traefik-test.flux-test.elifesciences.org"
    secretName: traefik-test.flux-test.elifesciences.org-tls
