apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-test
resources:
- namespace.yaml
- deployment.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: traefik-test
    app.kubernetes.io/instance: traefik-test
