apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amazon-network-flow-monitor
resources:
- namespace.yaml
- podmonitor.yaml


configMapGenerator:
- name: amazon-network-flow-monitor-dashboard
  files:
    - dashboards/amazon-network-flow-monitoring.json
  options:
    labels:
      grafana_dashboard: "1"
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: "disabled"
