apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../infra
- ../../ack-system
# - ../../capacitor
- ../../database
- ../../external-dns
- ../../external-secrets
- ../../gitops-dashboard
- ../../gemini
- ../../grafana
- ../../haproxy-kubernetes-ingress
- ../../keda
- ../../kong-system
- ../../kube-web-view
- ../../metrics-server
- ../../monitoring
- ../../nidhogg
- ../../spegel
- ../../template-controller
- ../../vector
- ../../victoriametrics
- ../../victorialogs
