apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- storageclasses
- volumesnapshotclasses
- secret-store
- ../base
- ../../aws-load-balancer-controller
# - ../../amazon-network-flow-monitor
